### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by abarba1953** [Embarcadero/ComparisonResearch#35]
1. There is NO file in directory:
\ComparisonResearch-main\calculator\delphi-fmx\monien\Engine
There is no unit: Calculator.Engine

2. Supplied EXE is not working. You can not enter number with more then 1 digit.

**Comment by omonien** [comment]
1. It looks like you missed that monien\Engine is actually a submodule. See .gitmodules in the repo's root.
To receive its code make sure do something like this:
`git pull --recurse-submodules`

2. Not sure what you mean by "supplied exe". There are no pre-compiled releases for this project on Github. You have to compile the executable by your self.
Anyway, the demo under delphi-fmx\monien is currently designed to handle scree/touch input only. No keyboard support that is. This is something that can easily be added though. 

Thanks for your feedback
Olaf Monien

**Comment by abarba1953** [comment]
Well, today files magically were in place under the directory Engine.
Yesterday I just downloaded complete ZIP and they were not there.

regards
Ante Barbarosa

**Comment by omonien** [comment]
Excellent!
Btw., I pushed an update today, which introduces basic keyboard support (besides mouse/touch input support). 
Regards
Olaf Monien
